### ISSUE TITLE
Round data for annual_precip_totals and mean_annual_snowfall coverages to one decimal place

### ISSUE THREAD

**Issue by kyleredilla** [ua-snap/rasdaman-ingest#34]
The data for the annual_precip_totals coverage, created with the `arctic_eds/annual_mean_pr/annual_pr_preprocessing.ipynb` notebook, and the mean_annual_snowfall coverage,  created with the `arctic_eds/annual_mean_snowfall/annual_mean_swe_preprocessing.ipynb` notebook, currently convert the native mm units to inches, in spirit of aligning with the original Atlas and engineer-preferred SI units. This decision might be subject to another GH issue, as it might make more sense to keep all data in Rasdaman in a single standard (metric / international or SI) for sake of simplicity, and worry about any conversion in the API. Anyway, the current processing rounds to the nearest integer, but it should round to the tenths place instead. This will obviously require using a float data type in place of the current 16-bit integer type used.

**Comment by charparr** [comment]
Update after today's tech chat regarding unit conversion and rounding strategy:

 - Rasdaman and the API receive data in SI units with appropriate and meaningful levels of precision.
 - API does rounding - not unit conversion.
 - Clients do the unit conversions and further rounding.
 
 An example:
 - `float32` precipitation GeoTIFFs in units of millimeters are ingested into Rasdaman
   - These are rounded to the nearest mm, but they'll still be over-precise because of the format.
 - The API returns the correct level of precision, i.e. `400 mm` and not `400.00000001 mm` and also rounds the results from any averaging or condensing that is done via the API.
 - The client receives these rounded values and does further analysis and rounds those results / and or converts to other units and rounds those units as needed (convert 400 mm to 40.0 cm or 15.7 inches)

I'll create issues as needed here and in the API for individual coverages / endpoints.
